### ISSUE TITLE
 Image reduction optimization

### ISSUE THREAD

**Issue by lemkoleg** [korlibs/korim#29]
Hello. Help me, please, with this question: I need
every time I get an image, reduce it to a certain
size (32Kb). I wrote such code. But I would like as much as possible
Optimize loss of quality and border design. Maybe you tell me
the best option? Here is my code:

private suspend fun getImmage32Kb(imageData: Bitmap32): ByteArray? {
        var bb: ByteArray? = null
        var image32: Bitmap32 = imageData
        var image16 = Bitmap16(width = image32.width, height = image32.height, format = RGB_565, premultiplied = false)
        val ex = ImageEncodingProps()
        bb = image32.encode(PNG, ex)
		val AVATAR_SIZE = 32768
        if (bb.size <= AVATAR_SIZE) return bb
        else bb = null
        image32.forEach { _, x, y ->
            image16.setRgba(x = x, y = y, v = image32.getRgba(x = x, y = y))
        }
        image32 = image16.toBMP32()
        GlobalScope.launch {
            var im_width = image32.width
            var im_heigth = image32.height
            var koef: Float
            val avatar = AVATAR_SIZE.toFloat()
            while (bb == null || bb!!.size > AVATAR_SIZE) {
                image32.forEach { _, x, y ->
                    image16.setRgba(x = x, y = y, v = image32.getRgba(x = x, y = y))
                }
                bb = image16.encode(PNG, ex)
                if (bb!!.size <= AVATAR_SIZE) break
                val percent = (bb!!.size / avatar)
                koef = if (percent >= 2.5F) {
                    1F
                } else {
                    0.98F
                }
                if (koef == 1F) {   
                    image32 = image32.mipmap(1)

                } else {
                    im_width = (im_width * koef).toInt()
                    im_heigth = (im_heigth * koef).toInt()
                    image32 = image32.copySliceWithSize(
                        (image32.width - im_width) / 2,
                        (image32.height - im_heigth) / 2,
                        im_width,
                        im_heigth
                    )

                }
                im_width = image32.width
                im_heigth = image32.height
                image16 =
                    Bitmap16(width = im_width, height = im_heigth, format = RGB_565, premultiplied = false)
            }

        }.join()
        return bb
    }

**Comment by soywiz** [comment]
If you don't need alpha channel, you can use JPEG that allows to adjust quality/size keeping the original image dimensions.

I would not use Bitmap16, since the generated PNG is 32-bit anyway, that would help a bit with compression.

Also Korim is not designed for image file optimization. It allows to render and transform images, but doesnt optimize huffman or png filters.

There are programs to do just that like jpegoptim or pngcrush. You would typically generate the image here or if you have it already and call an external image optimizers directly. For thumbnailing you can call the imagemagick cli directly. Or use korim, output the image to a jpeg or png file with maximum quality and call the external cli program optimizer

**Comment by lemkoleg** [comment]
Thank you. Can I email you if I have any questions about korlibs?


вс, 12 апр. 2020 г. в 19:01, Carlos Ballesteros Velasco <
notifications@github.com>:

**Comment by soywiz** [comment]
Sure. You can also join Slack and ask there: https://slack.soywiz.com/
